const countryList = [ 
    {country: 'Afghanistan', fees: 0, code: 'AF'}, 
    {country: 'Åland Islands', fees: 0, code: 'AX'}, 
    {country: 'Albania', fees: 0, code: 'AL'}, 
    {country: 'Algeria', fees: 0, code: 'DZ'}, 
    {country: 'American Samoa', fees: 0, code: 'AS'}, 
    {country: 'AndorrA', fees: 0, code: 'AD'}, 
    {country: 'Angola', fees: 0, code: 'AO'}, 
    {country: 'Anguilla', fees: 0, code: 'AI'}, 
    {country: 'Antarctica', fees: 0, code: 'AQ'}, 
    {country: 'Antigua and Barbuda', fees: 0, code: 'AG'}, 
    {country: 'Argentina', fees: 0, code: 'AR'}, 
    {country: 'Armenia', fees: 0, code: 'AM'}, 
    {country: 'Aruba', fees: 0, code: 'AW'}, 
    {country: 'Australia', fees: 0, code: 'AU'}, 
    {country: 'Austria', fees: 0, code: 'AT'}, 
    {country: 'Azerbaijan', fees: 0, code: 'AZ'}, 
    {country: 'Bahamas', fees: 0, code: 'BS'}, 
    {country: 'Bahrain', fees: 0, code: 'BH'}, 
    {country: 'Bangladesh', fees: 0, code: 'BD'}, 
    {country: 'Barbados', fees: 0, code: 'BB'}, 
    {country: 'Belarus', fees: 0, code: 'BY'}, 
    {country: 'Belgium', fees: 0, code: 'BE'}, 
    {country: 'Belize', fees: 0, code: 'BZ'}, 
    {country: 'Benin', fees: 0, code: 'BJ'}, 
    {country: 'Bermuda', fees: 0, code: 'BM'}, 
    {country: 'Bhutan', fees: 0, code: 'BT'}, 
    {country: 'Bolivia', fees: 0, code: 'BO'}, 
    {country: 'Bosnia and Herzegovina', fees: 0, code: 'BA'}, 
    {country: 'Botswana', fees: 0, code: 'BW'}, 
    {country: 'Bouvet Island', fees: 0, code: 'BV'}, 
    {country: 'Brazil', fees: 0, code: 'BR'}, 
    {country: 'British Indian Ocean Territory', fees: 0, code: 'IO'}, 
    {country: 'Brunei Darussalam', fees: 0, code: 'BN'}, 
    {country: 'Bulgaria', fees: 0, code: 'BG'}, 
    {country: 'Burkina Faso', fees: 0, code: 'BF'}, 
    {country: 'Burundi', fees: 0, code: 'BI'}, 
    {country: 'Cambodia', fees: 0, code: 'KH'}, 
    {country: 'Cameroon', fees: 0, code: 'CM'}, 
    {country: 'Canada', fees: 0, code: 'CA'}, 
    {country: 'Cape Verde', fees: 0, code: 'CV'}, 
    {country: 'Cayman Islands', fees: 0, code: 'KY'}, 
    {country: 'Central African Republic', fees: 0, code: 'CF'}, 
    {country: 'Chad', fees: 0, code: 'TD'}, 
    {country: 'Chile', fees: 0, code: 'CL'}, 
    {country: 'China', fees: 0, code: 'CN'}, 
    {country: 'Christmas Island', fees: 0, code: 'CX'}, 
    {country: 'Cocos (Keeling) Islands', fees: 0, code: 'CC'}, 
    {country: 'Colombia', fees: 0, code: 'CO'}, 
    {country: 'Comoros', fees: 0, code: 'KM'}, 
    {country: 'Congo', fees: 0, code: 'CG'}, 
    {country: 'Congo, The Democratic Republic of the', fees: 0, code: 'CD'}, 
    {country: 'Cook Islands', fees: 0, code: 'CK'}, 
    {country: 'Costa Rica', fees: 0, code: 'CR'}, 
    {country: 'Cote D\'Ivoire', fees: 0, code: 'CI'}, 
    {country: 'Croatia', fees: 0, code: 'HR'}, 
    {country: 'Cuba', fees: 0, code: 'CU'}, 
    {country: 'Cyprus', fees: 0, code: 'CY'}, 
    {country: 'Czech Republic', fees: 0, code: 'CZ'}, 
    {country: 'Denmark', fees: 0, code: 'DK'}, 
    {country: 'Djibouti', fees: 0, code: 'DJ'}, 
    {country: 'Dominica', fees: 0, code: 'DM'}, 
    {country: 'Dominican Republic', fees: 0, code: 'DO'}, 
    {country: 'Ecuador', fees: 0, code: 'EC'}, 
    {country: 'Egypt', fees: 0, code: 'EG'}, 
    {country: 'El Salvador', fees: 0, code: 'SV'}, 
    {country: 'Equatorial Guinea', fees: 0, code: 'GQ'}, 
    {country: 'Eritrea', fees: 0, code: 'ER'}, 
    {country: 'Estonia', fees: 0, code: 'EE'}, 
    {country: 'Ethiopia', fees: 0, code: 'ET'}, 
    {country: 'Falkland Islands (Malvinas)', fees: 0, code: 'FK'}, 
    {country: 'Faroe Islands', fees: 0, code: 'FO'}, 
    {country: 'Fiji', fees: 0, code: 'FJ'}, 
    {country: 'Finland', fees: 0, code: 'FI'}, 
    {country: 'France', fees: 0, code: 'FR'}, 
    {country: 'French Guiana', fees: 0, code: 'GF'}, 
    {country: 'French Polynesia', fees: 0, code: 'PF'}, 
    {country: 'French Southern Territories', fees: 0, code: 'TF'}, 
    {country: 'Gabon', fees: 0, code: 'GA'}, 
    {country: 'Gambia', fees: 0, code: 'GM'}, 
    {country: 'Georgia', fees: 0, code: 'GE'}, 
    {country: 'Germany', fees: 0, code: 'DE'}, 
    {country: 'Ghana', fees: 0, code: 'GH'}, 
    {country: 'Gibraltar', fees: 0, code: 'GI'}, 
    {country: 'Greece', fees: 0, code: 'GR'}, 
    {country: 'Greenland', fees: 0, code: 'GL'}, 
    {country: 'Grenada', fees: 0, code: 'GD'}, 
    {country: 'Guadeloupe', fees: 0, code: 'GP'}, 
    {country: 'Guam', fees: 0, code: 'GU'}, 
    {country: 'Guatemala', fees: 0, code: 'GT'}, 
    {country: 'Guernsey', fees: 0, code: 'GG'}, 
    {country: 'Guinea', fees: 0, code: 'GN'}, 
    {country: 'Guinea-Bissau', fees: 0, code: 'GW'}, 
    {country: 'Guyana', fees: 0, code: 'GY'}, 
    {country: 'Haiti', fees: 0, code: 'HT'}, 
    {country: 'Heard Island and Mcdonald Islands', fees: 0, code: 'HM'}, 
    {country: 'Holy See (Vatican City State)', fees: 0, code: 'VA'}, 
    {country: 'Honduras', fees: 0, code: 'HN'}, 
    {country: 'Hong Kong', fees: 0, code: 'HK'}, 
    {country: 'Hungary', fees: 0, code: 'HU'}, 
    {country: 'Iceland', fees: 0, code: 'IS'}, 
    {country: 'India', fees: 0, code: 'IN'}, 
    {country: 'Indonesia', fees: 0, code: 'ID'}, 
    {country: 'Iran, Islamic Republic Of', fees: 0, code: 'IR'}, 
    {country: 'Iraq', fees: 0, code: 'IQ'}, 
    {country: 'Ireland', fees: 0, code: 'IE'}, 
    {country: 'Isle of Man', fees: 0, code: 'IM'}, 
    {country: 'Israel', fees: 0, code: 'IL'}, 
    {country: 'Italy', fees: 0, code: 'IT'}, 
    {country: 'Jamaica', fees: 0, code: 'JM'}, 
    {country: 'Japan', fees: 0, code: 'JP'}, 
    {country: 'Jersey', fees: 0, code: 'JE'}, 
    {country: 'Jordan', fees: 0, code: 'JO'}, 
    {country: 'Kazakhstan', fees: 0, code: 'KZ'}, 
    {country: 'Kenya', fees: 0, code: 'KE'}, 
    {country: 'Kiribati', fees: 0, code: 'KI'}, 
    {country: 'Korea, Democratic People\'S Republic of', fees: 0, code: 'KP'}, 
    {country: 'Korea, Republic of', fees: 0, code: 'KR'}, 
    {country: 'Kuwait', fees: 0, code: 'KW'}, 
    {country: 'Kyrgyzstan', fees: 0, code: 'KG'}, 
    {country: 'Lao People\'S Democratic Republic', fees: 0, code: 'LA'}, 
    {country: 'Latvia', fees: 0, code: 'LV'}, 
    {country: 'Lebanon', fees: 0, code: 'LB'}, 
    {country: 'Lesotho', fees: 0, code: 'LS'}, 
    {country: 'Liberia', fees: 0, code: 'LR'}, 
    {country: 'Libyan Arab Jamahiriya', fees: 0, code: 'LY'}, 
    {country: 'Liechtenstein', fees: 0, code: 'LI'}, 
    {country: 'Lithuania', fees: 0, code: 'LT'}, 
    {country: 'Luxembourg', fees: 0, code: 'LU'}, 
    {country: 'Macao', fees: 0, code: 'MO'}, 
    {country: 'Macedonia, The Former Yugoslav Republic of', fees: 0, code: 'MK'}, 
    {country: 'Madagascar', fees: 0, code: 'MG'}, 
    {country: 'Malawi', fees: 0, code: 'MW'}, 
    {country: 'Malaysia', fees: 0, code: 'MY'}, 
    {country: 'Maldives', fees: 0, code: 'MV'}, 
    {country: 'Mali', fees: 0, code: 'ML'}, 
    {country: 'Malta', fees: 0, code: 'MT'}, 
    {country: 'Marshall Islands', fees: 0, code: 'MH'}, 
    {country: 'Martinique', fees: 0, code: 'MQ'}, 
    {country: 'Mauritania', fees: 0, code: 'MR'}, 
    {country: 'Mauritius', fees: 0, code: 'MU'}, 
    {country: 'Mayotte', fees: 0, code: 'YT'}, 
    {country: 'Mexico', fees: 0, code: 'MX'}, 
    {country: 'Micronesia, Federated States of', fees: 0, code: 'FM'}, 
    {country: 'Moldova, Republic of', fees: 0, code: 'MD'}, 
    {country: 'Monaco', fees: 0, code: 'MC'}, 
    {country: 'Mongolia', fees: 0, code: 'MN'}, 
    {country: 'Montserrat', fees: 0, code: 'MS'}, 
    {country: 'Morocco', fees: 0, code: 'MA'}, 
    {country: 'Mozambique', fees: 0, code: 'MZ'}, 
    {country: 'Myanmar', fees: 0, code: 'MM'}, 
    {country: 'Namibia', fees: 0, code: 'NA'}, 
    {country: 'Nauru', fees: 0, code: 'NR'}, 
    {country: 'Nepal', fees: 0, code: 'NP'}, 
    {country: 'Netherlands', fees: 0, code: 'NL'}, 
    {country: 'Netherlands Antilles', fees: 0, code: 'AN'}, 
    {country: 'New Caledonia', fees: 0, code: 'NC'}, 
    {country: 'New Zealand', fees: 0, code: 'NZ'}, 
    {country: 'Nicaragua', fees: 0, code: 'NI'}, 
    {country: 'Niger', fees: 0, code: 'NE'}, 
    {country: 'Nigeria', fees: 0, code: 'NG'}, 
    {country: 'Niue', fees: 0, code: 'NU'}, 
    {country: 'Norfolk Island', fees: 0, code: 'NF'}, 
    {country: 'Northern Mariana Islands', fees: 0, code: 'MP'}, 
    {country: 'Norway', fees: 0, code: 'NO'}, 
    {country: 'Oman', fees: 0, code: 'OM'}, 
    {country: 'Pakistan', fees: 0, code: 'PK'}, 
    {country: 'Palau', fees: 0, code: 'PW'}, 
    {country: 'Palestinian Territory, Occupied', fees: 0, code: 'PS'}, 
    {country: 'Panama', fees: 0, code: 'PA'}, 
    {country: 'Papua New Guinea', fees: 0, code: 'PG'}, 
    {country: 'Paraguay', fees: 0, code: 'PY'}, 
    {country: 'Peru', fees: 0, code: 'PE'}, 
    {country: 'Philippines', fees: 0, code: 'PH'}, 
    {country: 'Pitcairn', fees: 0, code: 'PN'}, 
    {country: 'Poland', fees: 0, code: 'PL'}, 
    {country: 'Portugal', fees: 0, code: 'PT'}, 
    {country: 'Puerto Rico', fees: 0, code: 'PR'}, 
    {country: 'Qatar', fees: 0, code: 'QA'}, 
    {country: 'Reunion', fees: 0, code: 'RE'}, 
    {country: 'Romania', fees: 0, code: 'RO'}, 
    {country: 'Russian Federation', fees: 0, code: 'RU'}, 
    {country: 'RWANDA', fees: 0, code: 'RW'}, 
    {country: 'Saint Helena', fees: 0, code: 'SH'}, 
    {country: 'Saint Kitts and Nevis', fees: 0, code: 'KN'}, 
    {country: 'Saint Lucia', fees: 0, code: 'LC'}, 
    {country: 'Saint Pierre and Miquelon', fees: 0, code: 'PM'}, 
    {country: 'Saint Vincent and the Grenadines', fees: 0, code: 'VC'}, 
    {country: 'Samoa', fees: 0, code: 'WS'}, 
    {country: 'San Marino', fees: 0, code: 'SM'}, 
    {country: 'Sao Tome and Principe', fees: 0, code: 'ST'}, 
    {country: 'Saudi Arabia', fees: 0, code: 'SA'}, 
    {country: 'Senegal', fees: 0, code: 'SN'}, 
    {country: 'Serbia and Montenegro', fees: 0, code: 'CS'}, 
    {country: 'Seychelles', fees: 0, code: 'SC'}, 
    {country: 'Sierra Leone', fees: 0, code: 'SL'}, 
    {country: 'Singapore', fees: 0, code: 'SG'}, 
    {country: 'Slovakia', fees: 0, code: 'SK'}, 
    {country: 'Slovenia', fees: 0, code: 'SI'}, 
    {country: 'Solomon Islands', fees: 0, code: 'SB'}, 
    {country: 'Somalia', fees: 0, code: 'SO'}, 
    {country: 'South Africa', fees: 0, code: 'ZA'}, 
    {country: 'South Georgia and the South Sandwich Islands', fees: 0, code: 'GS'}, 
    {country: 'Spain', fees: 0, code: 'ES'}, 
    {country: 'Sri Lanka', fees: 0, code: 'LK'}, 
    {country: 'Sudan', fees: 0, code: 'SD'}, 
    {country: 'Suricountry', fees: 0, code: 'SR'}, 
    {country: 'Svalbard and Jan Mayen', fees: 0, code: 'SJ'}, 
    {country: 'Swaziland', fees: 0, code: 'SZ'}, 
    {country: 'Sweden', fees: 0, code: 'SE'}, 
    {country: 'Switzerland', fees: 0, code: 'CH'}, 
    {country: 'Syrian Arab Republic', fees: 0, code: 'SY'}, 
    {country: 'Taiwan, Province of China', fees: 0, code: 'TW'}, 
    {country: 'Tajikistan', fees: 0, code: 'TJ'}, 
    {country: 'Tanzania, United Republic of', fees: 0, code: 'TZ'}, 
    {country: 'Thailand', fees: 0, code: 'TH'}, 
    {country: 'Timor-Leste', fees: 0, code: 'TL'}, 
    {country: 'Togo', fees: 0, code: 'TG'}, 
    {country: 'Tokelau', fees: 0, code: 'TK'}, 
    {country: 'Tonga', fees: 0, code: 'TO'}, 
    {country: 'Trinidad and Tobago', fees: 0, code: 'TT'}, 
    {country: 'Tunisia', fees: 0, code: 'TN'}, 
    {country: 'Turkey', fees: 0, code: 'TR'}, 
    {country: 'Turkmenistan', fees: 0, code: 'TM'}, 
    {country: 'Turks and Caicos Islands', fees: 0, code: 'TC'}, 
    {country: 'Tuvalu', fees: 0, code: 'TV'}, 
    {country: 'Uganda', fees: 0, code: 'UG'}, 
    {country: 'Ukraine', fees: 0, code: 'UA'}, 
    {country: 'United Arab Emirates', fees: 0, code: 'AE'}, 
    {country: 'United Kingdom', fees: 0, code: 'GB'}, 
    {country: 'United States', fees: 0, code: 'US'}, 
    {country: 'United States Minor Outlying Islands', fees: 0, code: 'UM'}, 
    {country: 'Uruguay', fees: 0, code: 'UY'}, 
    {country: 'Uzbekistan', fees: 0, code: 'UZ'}, 
    {country: 'Vanuatu', fees: 0, code: 'VU'}, 
    {country: 'Venezuela', fees: 0, code: 'VE'}, 
    {country: 'Viet Nam', fees: 0, code: 'VN'}, 
    {country: 'Virgin Islands, British', fees: 0, code: 'VG'}, 
    {country: 'Virgin Islands, U.S.', fees: 0, code: 'VI'}, 
    {country: 'Wallis and Futuna', fees: 0, code: 'WF'}, 
    {country: 'Western Sahara', fees: 0, code: 'EH'}, 
    {country: 'Yemen', fees: 0, code: 'YE'}, 
    {country: 'Zambia', fees: 0, code: 'ZM'}, 
    {country: 'Zimbabwe', fees: 0, code: 'ZW'} 
  ]

  module.exports = {countryList}